version: "3.8"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: . 
    ports:
      - "4000:4000"  
    depends_on:
      - db  
    environment:
      DATABASE_URL: mysql://root:password@db:3306/my_database  
    volumes:
      - .:/app  
    command: npm run dev  

volumes:
  db_data:
